stages:
  - format
  - lint
  - test
  - coverage
  - build
  - bench
  - doc

test:lint:rustfmt:
  stage: format
  image: "thatonelutenist/rust-nathan:latest"
  script:
    - cargo fmt --all -- --check
  tags:
    - linux
  allow_failure: true
  when: always
    
test:lint:clippy:
  stage: lint
  image: "thatonelutenist/rust-nathan:latest"
  script:
    - cargo clippy -- -D warnings
  tags:
    - linux
  allow_failure: true
  needs: ["test:lint:rustfmt"]

    
test:test:linux:
  stage: test
  image: "thatonelutenist/rust-nathan:latest"
  script:
    - rustc --version
    - cargo --version
    - cargo junit --name linux.xml
  cache:
    key: "$CI_COMMIT_REF_SLUG-test"
    paths:
      - ~/.cargo
      - target
  tags:
    - linux
  needs: ["test:lint:rustfmt"]
  allow_failure: true
  artifacts:
    paths:
      - linux.xml
    reports:
      junit: linux.xml

test:test:windows:
  stage: test
  script:
    - rustc --version
    - cargo --version
    - cargo test 
  cache:
    key: "$CI_COMMIT_REF_SLUG-test"
    paths:
      - ~/.cargo
      - target
  tags:
    - windows
  needs: ["test:lint:rustfmt"]
  allow_failure: true
  only:
    - master
    - tags

test:coverage:
  stage: coverage
  image: "thatonelutenist/rust-nathan:latest"
  script:
    - cargo check
    - cd asuran-core
    - cargo kcov
    - cd ../asuran
    - cargo kcov
    - cd ..
    - bash <(curl -s https://codecov.io/bash) -s target/cov
  cache:
    key: "$CI_COMMIT_REF_SLUG-cov"
    paths:
      - ~/.cargo
      - target
  tags:
    - linux
  needs: ["test:test:linux"]

build:build:linux:
  stage: build
  image: "thatonelutenist/rust-nathan:latest"
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/
  cache:
    key: "$CI_COMMIT_REF_SLUG-build"
    paths:
      - ~/.cargo
      - target
  tags:
    - linux
  needs: ["test:test:linux"]
  only:
    - master
    - tags

build:build:windows:
  stage: build
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/
  cache:
    key: "$CI_COMMIT_REF_SLUG-build"
    paths:
      - ~/.cargo
      - target
  tags:
    - windows
  needs: ["test:test:windows"]
  only:
    - master
    - tags

build:bench:linux:
  stage: bench
  image: "thatonelutenist/rust-nathan:latest"
  variables:
    RUSTFLAGS: "-C target-cpu=native"
  script:
    - cargo bench
  cache:
    key: "$CI_COMMIT_REF_SLUG-bench"
    paths:
      - ~/.cargo
      - target
  tags:
    - linux
  needs: ["build:build:linux"]
  only:
    - master
    - tags

build:bench:windows:
  stage: bench
  variables:
    RUSTFLAGS: "-C target-cpu=native"
  script:
    - cargo bench
  cache:
    key: "$CI_COMMIT_REF_SLUG-bench"
    paths:
      - ~/.cargo
      - target
  tags:
    - windows
  needs: ["build:build:windows"]
  only:
    - master
    - tags

pages:
  stage: doc
  image: "thatonelutenist/rust-nathan:latest"
  script:
    - cargo doc --no-deps --document-private-items
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0; url=libasuran">' > public/index.html
  artifacts:
    paths:
      - public
      - target
  needs: ["test:lint:rustfmt"]
  tags:
    - linux
  when: always
