image: "thatonelutenist/rust-nathan:latest"

stages:
  - lint
  - test
  - build
  - doc

clippy:
  stage: lint
  script:
    - cargo clippy -- -D warnings


rustfmt:
  stage: lint
  script:
    - cargo fmt --all -- --check

test:
  stage: test
  script:
    - rustc --version
    - cargo --version
    - cargo test --verbose

build_job:
  stage: build
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/

pages:
  stage: doc
  script:
    - cargo doc --no-deps
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0; url=libasuran">' > public/index.html
  artifacts:
    paths:
      - public
      - target

tarpaulin:
  stage: test
  script:
    - cargo clean
    - cargo tarpaulin --out Xml
    - bash <(curl -s https://codecov.io/bash)
