stages:
  - test
  - build
  - doc

test:lint:clippy:
  stage: test
  image: "thatonelutenist/rust-nathan:latest"
  script:
    - cargo clippy -- -D warnings
  tags:
    - linux

test:lint:rustfmt:
  stage: test
  image: "thatonelutenist/rust-nathan:latest"
  script:
    - cargo fmt --all -- --check
  tags:
    - linux

test:test:linux:
  stage: test
  image: "thatonelutenist/rust-nathan:latest"
  script:
    - rustc --version
    - cargo --version
    - cargo junit --name linux.xml
  cache:
    key: "$CI_COMMIT_REF_SLUG-test"
    paths:
      - ~/.cargo
      - target
  artifacts:
    paths:
      - linux.xml
    reports:
      junit: linux.xml
  tags:
    - linux

test:test:windows:
  stage: test
  script:
    - rustc --version
    - cargo --version
    - cargo junit --name windows.xml
  cache:
    key: "$CI_COMMIT_REF_SLUG-test"
    paths:
      - ~/.cargo
      - target
  artifacts:
    paths:
      - windows.xml
    reports:
      junit: windows.xml
  tags:
    - windows

test:tarpaulin:
  stage: test
  image: "thatonelutenist/rust-nathan:latest"
  script:
    - cargo tarpaulin --out Xml -t 600 --ignore-tests --force-clean
    - bash <(curl -s https://codecov.io/bash)
  cache:
    key: "$CI_COMMIT_REF_SLUG-tarp"
    paths:
      - ~/.cargo
      - target
  tags:
    - linux 

build:build:linux:
  stage: build
  image: "thatonelutenist/rust-nathan:latest"
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/
  cache:
    key: "$CI_COMMIT_REF_SLUG-build"
    paths:
      - ~/.cargo
      - target
  tags:
    - linux

build:build:windows:
  stage: build
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/
  cache:
    key: "$CI_COMMIT_REF_SLUG-build"
    paths:
      - ~/.cargo
      - target
  tags:
    - windows

build:bench:linux:
  stage: build
  image: "thatonelutenist/rust-nathan:latest"
  variables:
    RUSTFLAGS: "-C target-cpu=native"
  script:
    - cargo bench
  cache:
    key: "$CI_COMMIT_REF_SLUG-bench"
    paths:
      - ~/.cargo
      - target
  tags:
    - linux

build:bench:windows:
  stage: build
  variables:
    RUSTFLAGS: "-C target-cpu=native"
  script:
    - cargo bench
  cache:
    key: "$CI_COMMIT_REF_SLUG-bench"
    paths:
      - ~/.cargo
      - target
  tags:
    - windows

doc:pages:
  stage: doc
  image: "thatonelutenist/rust-nathan:latest"
  script:
    - cargo doc --no-deps
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0; url=libasuran">' > public/index.html
  artifacts:
    paths:
      - public
      - target
  tags:
    - linux 



