image: "rust:latest"

before_script:
  - apt-get update -yqq
  - apt-get install -yqq --no-install-recommends build-essential
  - apt-get install -yqq clang
  - apt-get install -yqq tree

cache:
  paths:
    - target

stages:
  - test
  - build
  - doc

test:
  stage: test
  script:
    - rustc --version
    - cargo --version
    - cargo test --verbose

build_job:
  stage: build
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/

pages:
  stage: doc
  script:
    - cargo doc --no-deps
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0; url=libasuran">' > public/index.html
    
  artifacts:
    paths:
      - public
      