stages:
  - lint
  - test
  - build
  - doc

lint:clippy:
  stage: lint
  image: "thatonelutenist/rust-nathan:latest"
  script:
    - cargo clippy -- -D warnings
  tags:
    - linux

lint:rustfmt:
  stage: lint
  image: "thatonelutenist/rust-nathan:latest"
  script:
    - cargo fmt --all -- --check
  tags:
    - linux

test:test:
  stage: test
  image: "thatonelutenist/rust-nathan:latest"
  script:
    - rustc --version
    - cargo --version
    - cargo test --verbose
  cache:
    key: "$CI_COMMIT_REF_SLUG-test"
    paths:
      - ~/.cargo
      - target
  tags:
    - linux

test:tarpaulin:
  stage: test
  image: "thatonelutenist/rust-nathan:latest"
  script:
    - cargo tarpaulin --out Xml -t 360 --ignore-tests --force-clean
    - bash <(curl -s https://codecov.io/bash)
  cache:
    key: "$CI_COMMIT_REF_SLUG-tarp"
    paths:
      - ~/.cargo
      - target
  tags:
    - linux 

build:build:linux:
  stage: build
  image: "thatonelutenist/rust-nathan:latest"
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/
  cache:
    key: "$CI_COMMIT_REF_SLUG-build"
    paths:
      - ~/.cargo
      - target
  tags:
    - linux

build:bench:linux:
  stage: build
  image: "thatonelutenist/rust-nathan:latest"
  variables:
    RUSTFLAGS: "-C target-cpu=native"
  script:
    - cargo bench
  cache:
    key: "$CI_COMMIT_REF_SLUG-bench"
    paths:
      - ~/.cargo
      - target
  tags:
    - linux

doc:pages:
  stage: doc
  image: "thatonelutenist/rust-nathan:latest"
  script:
    - cargo doc --no-deps
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0; url=libasuran">' > public/index.html
  artifacts:
    paths:
      - public
      - target
  tags:
    - linux 



