stages:
  - lint
  - test
  - coverage
  - build
  - doc

include:
  - local: '/ci/lint.yml'
  - local: '/ci/linux.yml'
  - local: '/ci/windows.yml'
  - local: '/ci/macos.yml'
    
test:coverage:
  stage: coverage
  image: "xd009642/tarpaulin"
  script:
    - apt-get update
    - apt-get install curl git -y
    - cargo tarpaulin --out Xml -t 600 --ignore-tests --force-clean --output-dir tarp
  after_script:
    - bash <(curl -s https://codecov.io/bash) -f tarp/cobertura.xml
  tags:
    - linux-own
  allow_failure: true
  needs: []

pages:
  stage: doc
  image: "guangie88/rustfmt-clippy:stable"
  script:
    - cargo doc --no-deps --document-private-items
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0; url=asuran">' > public/index.html
  artifacts:
    paths:
      - public
      - target
  needs: []
  tags:
    - linux
  only:
    - master
