image: "thatonelutenist/rust-tarp:20191202"

stages:
  - lint
  - test
  - build
  - doc

clippy:
  stage: lint
  script:
    - rustup component add clippy
    - cargo clippy -- -D warnings
  cache:
    paths:
      - target

test:
  stage: test
  script:
    - rustc --version
    - cargo --version
    - cargo test --verbose
  cache:
    paths:
      - target

build_job:
  stage: build
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/
  cache:
    paths:
      - target

pages:
  stage: doc
  script:
    - cargo doc --no-deps
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0; url=libasuran">' > public/index.html
  artifacts:
    paths:
      - public
  cache:
    paths:
      - target

tarpaulin:
  stage: test
  script:
    - cargo tarpaulin --out Xml
    - bash <(curl -s https://codecov.io/bash)
