image: "rust:latest"

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

cache:
  paths:
    - target
    - .cargo
  
before_script:
  - apt-get update -yqq
  - apt-get install -yqq --no-install-recommends build-essential
  - apt-get install -yqq clang
  - apt-get install -yqq tree

stages:
  - test
  - cover
  - build
  - doc

test:
  stage: test
  script:
    - rustc --version
    - cargo --version
    - cargo test --verbose

build_job:
  stage: build
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/

pages:
  stage: doc
  script:
    - cargo doc --no-deps
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0; url=libasuran">' > public/index.html
    
  artifacts:
    paths:
      - public

tarpaulin:
  stage: cover
  script:
    - cargo install cargo-tarpaulin -f
    - cargo tarpaulin --out Xml
    - bash <(curl -s https://codecov.io/bash)
  
  
      
