image: "thatonelutenist/rust-nathan:latest"

stages:
  - lint
  - test
  - build
  - doc

clippy:
  stage: lint
  script:
    - cargo clippy -- -D warnings

rustfmt:
  stage: lint
  script:
    - cargo fmt --all -- --check

test:
  stage: test
  script:
    - rustc --version
    - cargo --version
    - cargo test --verbose
  cache:
    key: "$CI_COMMIT_REF_SLUG-test"
    paths:
      - ~/.cargo
      - target

build_job:
  stage: build
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/
  cache:
    key: "$CI_COMMIT_REF_SLUG-build"
    paths:
      - ~/.cargo
      - target

pages:
  stage: doc
  script:
    - cargo doc --no-deps
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0; url=libasuran">' > public/index.html
  artifacts:
    paths:
      - public
      - target

tarpaulin:
  stage: test
  script:
    - cargo tarpaulin --out Xml -t 360 --ignore-tests --force-clean
    - bash <(curl -s https://codecov.io/bash)
  cache:
    key: "$CI_COMMIT_REF_SLUG-tarp"
    paths:
      - ~/.cargo
      - target

bench:
  stage: build
  variables:
    RUSTFLAGS: "-C target-cpu=native lto"
  script:
    - cargo bench
  cache:
    key: "$CI_COMMIT_REF_SLUG-bench"
    paths:
      - ~/.cargo
      - target
