[package]
name = "asuran"
description = "Deduplicating, encrypting, fast, and tamper evident archive format"
license = "MIT"
version = "0.0.4"
repository = "https://gitlab.com/asuran-rs/libasuran/"
documentation = "https://docs.rs/crate/libasuran"
homepage = "https://asuran.rs"
authors = ["Nathan McCarty <nathan@mccarty.io>"]
readme = "README-output.md"
edition = "2018"
keywords = ["encryption", "compression","deduplication","backup","archive"]

[features]
profile = ["flame", "flamer"]

[dependencies]
aes = "0.3.2"
aes-ctr = "0.3.0"
anyhow = "1.0.26"
async-trait = "0.1.22"
base64 = "0.11.0"
bincode = "1.2.1"
blake2b_simd = "0.5.10"
blake3 = "0.1.2"
block-modes = "0.3.3"
byteorder = "1.3.2"
chacha20 = "0.3.3"
chrono = { version = "0.4.10", features = ["serde"] }
digest = "0.8.1"
fastcdc = "1.0.2"
flame = { version = "0.2.2", optional = true }
flamer = { version = "0.4.0", optional = true }
futures = { version = "0.3.1", default-features = false, features = ["std"] }
futures-intrusive = "0.2.2"
hmac = "0.7.1"
lazy_static = "1.4.0"
lru = { version = "0.4.3", default-features = false }
lz4 = "1.23.1"
num_cpus = "1.12.0"
petgraph = "0.5.0"
rand = { version = "0.7.3", features = ["small_rng"] }
rmp-serde = "0.14.0"
rust-argon2 = "0.6.1"
serde = { version = "1.0.104", features = ["derive", "rc"] }
serde_bytes = "0.11.3"
sha2 = "0.8.1"
sha3 = "0.8.2"
tokio = { version = "0.2.9", features = ["rt-core","rt-threaded", "macros", "sync", "blocking"] }
tracing = "0.1.12"
tracing-futures = "0.2.1"
uuid = { version = "0.8.1", features = ["serde", "v4"] }
walkdir = "2.3.1"
xz2 = "0.1.6"
zeroize = { version = "1.1.0", features = ["zeroize_derive"] }
zstd = "0.5.1"

[dev-dependencies]
criterion = "0.3.0"
dir-diff = "0.3.2"
futures-await-test = "0.3.0"
quickcheck = "0.9.2"
quickcheck_macros = "0.9.1"
tempfile = "3.1.0"

[[bench]]
name = "rawchunking"
harness = false


[[bench]]
name = "chunkandstore"
harness = false

[[bench]]
name = "archive"
harness = false


