[package]
name = "asuran-chunker"
description = "A general API for describing types that can break data in to chunks in repeatable ways"
license = "MIT"
version = "0.0.4"
repository = "https://gitlab.com/asuran-rs/asuran/"
documentation = "https://docs.rs/crate/asuran"
homepage = "https://asuran.rs"
authors = ["Nathan McCarty <nathan@mccarty.io>"]
edition = "2018"

[dependencies]
fastcdc = "1.0.2"
rand = { version = "0.7.3", features = ["small_rng"] }
thiserror = "1.0.10"

